USE [FRMORCOUS]
GO

/****** Object:  Table [dbo].[RENT]    Script Date: 5/30/2022 11:27:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RENT](
	[RENT_ID] [int] NOT NULL,
	[client_id] [int] NOT NULL,
	[gameID] [int] NOT NULL,
	[RentDate] [datetime] NULL,
	[ReturnDate] [datetime] NULL,
 CONSTRAINT [PK_RENT] PRIMARY KEY CLUSTERED 
(
	[RENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RENT]  WITH CHECK ADD  CONSTRAINT [FK_RENT_CLIENT] FOREIGN KEY([client_id])
REFERENCES [dbo].[CLIENT] ([CLIENT_ID])
GO

ALTER TABLE [dbo].[RENT] CHECK CONSTRAINT [FK_RENT_CLIENT]
GO

ALTER TABLE [dbo].[RENT]  WITH CHECK ADD  CONSTRAINT [FK_RENT_GAME1] FOREIGN KEY([gameID])
REFERENCES [dbo].[GAME] ([GAME_ID])
GO

ALTER TABLE [dbo].[RENT] CHECK CONSTRAINT [FK_RENT_GAME1]
GO


