USE [FRMORCOUS]
GO

/****** Object:  Table [dbo].[GAME]    Script Date: 5/30/2022 11:17:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GAME](
	[GAME_ID] [int] NOT NULL,
	[ADMIN_ID] [int] NOT NULL,
	[GAME_NAME] [varchar](30) NOT NULL,
	[PALTFORM] [varchar](30) NOT NULL,
	[CATEGORY] [varchar](30) NOT NULL,
	[YEARG] [int] NOT NULL,
	[vendor_name] [varchar](30) NULL,
	[RATE] [int] NOT NULL,
 CONSTRAINT [PK_GAME] PRIMARY KEY CLUSTERED 
(
	[GAME_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GAME]  WITH CHECK ADD  CONSTRAINT [FK_GAME_ADMIN] FOREIGN KEY([ADMIN_ID])
REFERENCES [dbo].[ADMIN] ([ADMIN_ID])
GO

ALTER TABLE [dbo].[GAME] CHECK CONSTRAINT [FK_GAME_ADMIN]
GO


