USE [FRMORCOUS]
GO

/****** Object:  Table [dbo].[CLIENT]    Script Date: 5/30/2022 11:17:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENT](
	[CLIENT_ID] [int] NOT NULL,
	[FIRSRT_NAMEC] [varchar](30) NOT NULL,
	[LAST_NAMEC] [varchar](30) NOT NULL,
	[EMAILC] [varchar](30) NOT NULL,
	[PASSWORDC] [varchar](30) NOT NULL,
	[ADDRESSC] [varchar](30) NOT NULL,
	[DAYC] [int] NOT NULL,
	[MONTHC] [int] NOT NULL,
	[YEARC] [int] NOT NULL,
 CONSTRAINT [PK_CLIENT] PRIMARY KEY CLUSTERED 
(
	[CLIENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


