USE [FRMORCOUS]
GO

/****** Object:  Table [dbo].[ADMIN]    Script Date: 5/30/2022 11:15:21 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ADMIN](
	[ADMIN_ID] [int] NOT NULL,
	[FIRST_NAME] [varchar](30) NOT NULL,
	[SECOND_NAME] [varchar](30) NOT NULL,
	[EMAIL] [varchar](30) NOT NULL,
	[PASSWORD] [varchar](30) NOT NULL,
	[ADDRESS] [varchar](30) NOT NULL,
	[DAY] [int] NOT NULL,
	[MONTH] [int] NOT NULL,
	[YEAR] [int] NOT NULL,
 CONSTRAINT [PK_ADMIN] PRIMARY KEY CLUSTERED 
(
	[ADMIN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


