USE [FRMORCOUS]
GO

/****** Object:  Table [dbo].[VENDOR]    Script Date: 5/30/2022 11:28:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VENDOR](
	[VENDRO_ID] [int] NOT NULL,
	[FIRST_NAMEV] [varchar](30) NOT NULL,
	[LAST_NAMEV] [varchar](30) NOT NULL,
	[EMAILV] [varchar](30) NOT NULL,
	[PASSV] [varchar](30) NOT NULL,
	[ADDRESSV] [varchar](30) NOT NULL,
	[DAYV] [int] NOT NULL,
	[MONTHV] [int] NOT NULL,
	[YEARV] [int] NOT NULL,
 CONSTRAINT [PK_VENDOR] PRIMARY KEY CLUSTERED 
(
	[VENDRO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


